---
# tasks for routeros updates validation

- name: Get routeros facts
  community.routeros.facts:
    gather_subset: all

- name: Get Firmware
  community.routeros.command:
    commands: /system routerboard print
  register: output

- name: Get Current Firmware Line
  set_fact:
    current: "{{ item | replace('current-firmware: ', '') | trim }}"
  when: "'current-firmware:' in item"
  loop: "{{ output.stdout_lines[0] }}"
  no_log: true

- name: Verify RouterOS and Firmware Versions Match
  ansible.builtin.assert:
    that:
      - ansible_net_version.split(' ')[0] is version(current, 'eq')
    fail_msg: "RouterOS version {{ ansible_net_version.split(' ')[0] }} does not match firmware version {{ current }}!"
    success_msg: "RouterOS version {{ ansible_net_version.split(' ')[0] }} matches firmware!"

- name: Validate RouterOS version matches {{ routeros_version }}
  ansible.builtin.assert:
    that:
      - ansible_net_version.split(' ')[0] is version(routeros_version, 'eq')
    fail_msg: "RouterOS version {{ ansible_net_version.split(' ')[0] }} does not match specified version {{ routeros_version }}"
    success_msg: "RouterOS version {{ ansible_net_version.split(' ')[0] }} matches specified version!"
